// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGrzlzlPi89d9gxN0Hj3Ty5HZAA-ZNwsQ',
    appId: '1:396752002467:web:12916a4977246be0a0ce16',
    messagingSenderId: '396752002467',
    projectId: 'cravinzo-56ad4',
    authDomain: 'cravinzo-56ad4.firebaseapp.com',
    databaseURL: 'https://cravinzo-56ad4-default-rtdb.firebaseio.com',
    storageBucket: 'cravinzo-56ad4.firebasestorage.app',
    measurementId: 'G-4VEXEG3EN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0G__XHbzfJWld4c9gpG0q6ZzRZzNh6wI',
    appId: '1:396752002467:android:cb6c9de9d92d7d84a0ce16',
    messagingSenderId: '396752002467',
    projectId: 'cravinzo-56ad4',
    databaseURL: 'https://cravinzo-56ad4-default-rtdb.firebaseio.com',
    storageBucket: 'cravinzo-56ad4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4zvka-PYWbu4dlQxh1afcfwOAdHEOwmQ',
    appId: '1:396752002467:ios:658a3e4a2a49dc2ea0ce16',
    messagingSenderId: '396752002467',
    projectId: 'cravinzo-56ad4',
    databaseURL: 'https://cravinzo-56ad4-default-rtdb.firebaseio.com',
    storageBucket: 'cravinzo-56ad4.firebasestorage.app',
    iosClientId: '396752002467-a13k137998m46brqkkppuo48q20poiq8.apps.googleusercontent.com',
    iosBundleId: 'com.cravinzo.deliverypartner',
  );
}
